### ISSUE TITLE
Stuck in blockheight of 22490

### ISSUE THREAD

**Issue by f5i23q999d** [DenrianWeiss/bellman#1]
2023/12/26 15:00:46 Scanning block 22490
2023/12/26 15:00:47 Body: {"result":{"hash":"3bf59a33eca68eba660aeb8a203af6cf3dfc807e1b9fbe336ebfdfece1d4490d","confirmations":509,"size":3913,"height":22490,"version":536870916,"merkleroot":"bab562904ca05486d0d73759c72aba01aadb8ef0063130b307de8d944bfd018e","tx":["f936294cc970a708f2ebbbcc65e0cc8ea1730c26ab884301cee976c46b8b5c12","49bf798973ed122b20983a24a9b5669b12389cf66ae57e0e6ec80e1781270ad9","2b14ef8ca9fadcc0988faec94e14b73971b6e28c21b585917871b2114938ae4d","7a9f51a87e52c214445025d6ecd7095c13b2a4584d3f23c40f2c659313538896","a33eddbfb700301038f2e25d34cbe2b55c1602d4138967f37759c9227d6d0b29","c7bb15e9f5a97c01abbe131b8b45c49ccb6996537c3f89b4f9306e7a4a9d3306","00c9085f6f7b9cb92735c83d902ec117c4282e0bc28fd60270d90355307f5a8a"],"time":1703542850,"nonce":3746086363,"bits":"1a0b1578","difficulty":1513638.43566559,"previousblockhash":"12525352c7e0babeb7dc092fa6707a96eb3bebab776c39feb9ed39245f9e9ce6","nextblockhash":"33db5f68fc9e6497b21df6988d0d8e35f3501d08cb9942ffb3d172b798d23e44"},"error":null,"id":1}
2023/12/26 15:00:47 Body: {"result":"01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff1e02da570442008a65001de2df96451d01000c2f4d696e696e67436f72652f00000000020000000000000000266a24aa21a9ed8ff2b7ce67f663087b6edf909f8de3dc5a88707e10ef59fb0ac195a6b37f4edaab126457020000001976a9149ab8e84373e9fe1adaac9db9c3a67a375458105288ac00000000","error":null,"id":1}
2023/12/26 15:00:47 Error scanning blocks: no address found

**Comment by DenrianWeiss** [comment]
Current revision does not support non-standard tx like OP_RETURN, will add support later

**Comment by DenrianWeiss** [comment]
Fixed, please re-compile and replace binary with new revision.
